name: Windows (x64)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: cmd
      run: call ./windows.bat
    - name: Archive v8_monolith
      uses: actions/upload-artifact@v3
      with:
        name: v8_monolith
        path: v8/v8/out/windows/obj/v8_monolith.lib
